### ISSUE TITLE
Crash when opening Hammer Table if Backpack(Eydamos) is installed

### ISSUE THREAD

**Issue by drakray** [thebrightspark/SparksHammers#11]
As seens [here](https://minecraft.curseforge.com/projects/forge-backpacks/issues/1)
Recent [crash](http://pastebin.com/CzzqQCfL)
MC 1.10.2
backpack-3.0.1-1.10.2.jar
SparksHammers-1.10.2-1.4.4.jar
and many more, but irrelevant
Seems to come from something your side, as any other inventory(that i tried) open nicely

**Comment by thebrightspark** [comment]
Sorry I have only come back to this issue now. I have tested using the latest versions (listed below) and I can't replicate it.
Sparks Hammers v1.6.3.1
Backpacks v3.0.1

Can you confirm if this is still an issue please?

**Comment by drakray** [comment]
I can't confirm with recent version as I no longer use Eydamos's Backpack, but if you test it and it donesn't crash, then it's fixed :D (as it ALWAYS crashed with only those 2 mods installed)

**Comment by thebrightspark** [comment]
Alright fair enough. Thanks for the reply :)
