### ISSUE TITLE
[1.11-1.4.4.1] odd crash, probably because my server is 1.11.2

### ISSUE THREAD

**Issue by kreezxil** [thebrightspark/SparksHammers#12]
Not sure if this was supposed to run in 1.11.2, swore you had it tagged for 1.11.2 back when I started my pack. Anyhow 38 versions later and I finally get an error 1.11.2.

If it is not meant to run in 1.11.2, let me know and close the issue, it's fine. Otherwise ... have fun! :)

**Comment by thebrightspark** [comment]
I've just updated the mod to 1.11.2, so have a go with that and let me know how it goes :)

Any issues, make sure you post appropriate logs please.

**Comment by thebrightspark** [comment]
I'm going to presume this isn't an issue anymore and close this, especially since I have official 1.11.2 versions.
