### ISSUE TITLE
[1.11.2-1.6.2] Hammer Crafting Table uncraftable.

### ISSUE THREAD

**Issue by Trinsec** [thebrightspark/SparksHammers#13]
I'm using the latest version (1.6.2 for 1.11.2) in the Curse client. When I try to make a wooden hammer, the recipe for the Wooden Hammer Head doesn't exist. No biggy, I'll just go make a Hammer Crafting Table then.. except.. that also requires the Wooden Hammer, so I'm stuck with not being able to make hammers. The only thing I can use right now is a Wood Excavator.

**Comment by thebrightspark** [comment]
Hmm okay. Looks like I derped a little with the recipe. It'll be fixed in the next version

**Comment by thebrightspark** [comment]
This was fixed for version 1.6.3
https://github.com/thebrightspark/SparksHammers/commit/2025327c10492e90d511673752b2cba3994ffffa
