### ISSUE TITLE
[1.11.2-1.6.2] Uncraftable Hammers showing up in JEI.

### ISSUE THREAD

**Issue by Trinsec** [thebrightspark/SparksHammers#14]
Some hammers show up in JEI that only shows the wooden shaft in the Hammer's crafting table, and no head. For example, Lead Hammer, lead is not a material available in my world. Shouldn't those uncraftable hammers be left out of the JEI if the world doesn't support the materials for them? Using 1.6.2.

**Comment by thebrightspark** [comment]
Ah yes, they should have been removed from JEI, however due to my changes with the way tools are registered in the most recent versions it seems to have brought about this error. I'll sort it out for the next version.

**Comment by thebrightspark** [comment]
Actually, can you tell me all of the mods (and their versions) that you have also installed? Also any changes to the customTools.json? This doesn't seem to be an issue with just Sparks Hammers and JEI with all default configs. All of the tools which can't be crafted are correctly removed from JEI.

**Comment by Trinsec** [comment]
Sure thing. It's a default installation, so no changes made to its config. List of mods attached below. This is the current status of my mods while I see the uncraftable hammers in the JEI.

[modslist.txt](https://github.com/thebrightspark/SparksHammers/files/795836/modslist.txt)

**Comment by thebrightspark** [comment]
Just coming back to this issue, and I realise going through those mods will be long XD Do you happen to know (or at least be able to check in JEI) which of your mods add new metals and ores? I want to get those mods and test with them and see if I can reproduce the issue.

**Comment by thebrightspark** [comment]
Bit of an old issue, but I have fixed this in v1.6.6 (only MC 1.12 atm)
