### ISSUE TITLE
[1.11.2-1.6.3] All recipes missing except crafting table

### ISSUE THREAD

**Issue by Dissgruntled** [thebrightspark/SparksHammers#17]
After updating to the latest version, all my hammers and excavators disappeared and cannot be crafted.
![2017-03-13_23 35 16](https://cloud.githubusercontent.com/assets/19914628/23888635/3d107c04-0846-11e7-8dff-835451e6e16a.png)

**Comment by thebrightspark** [comment]
Could you try deleting your customTools.json and let it generate the default file?

**Comment by Dissgruntled** [comment]
That fixed it.

**Comment by thebrightspark** [comment]
Great, thanks for letting me know :)

**Comment by drakray** [comment]
I got that too, maybe you should mention it on Curse, to prevent bad surprise

**Comment by thebrightspark** [comment]
Yes I will do, I'm just a bit busy today so I'll get round to it asap.
