### ISSUE TITLE
Missing Hammer in 1.11.2 1.6.3

### ISSUE THREAD

**Issue by drakray** [thebrightspark/SparksHammers#18]
http://pastebin.com/raw/z8zx7PRD

Full [forge.log](https://www.dropbox.com/s/8k2xhkyziieflsy/fml-client-latest%20201703141615.log?dl=0)

**Comment by thebrightspark** [comment]
Ah whoops! Sorry about that silly mistake. Fixed now for 1.6.3.1.
https://github.com/thebrightspark/SparksHammers/commit/3d718f26f6490c45b982770f60319f9c93e62b75
