### ISSUE TITLE
Charging Powered Hammer

### ISSUE THREAD

**Issue by jubalearly** [thebrightspark/SparksHammers#21]
Tested in both 1.11.2 and 1.10.2 and cannot find a compatible way to charge the powered hammers.  Not chargeable in Actually Additions energizer, RFtools power cube, Mekanism (1.10.2) cube or energetic infuser from TE (1.10.2)

**Comment by thebrightspark** [comment]
Hmm okay, well I'm using Forge Energy for it and tbh I haven't tested it with many mods (I don't know many different energy mods with chargers). I can add the RF API for it specifically if needed and that should allow it to be charged by most mods.

I just thought more mods would have added compatibility for FE by now. Unless I've not implemented it correctly, but I'm sure I have XD

Do you happen to know of any mods that specifically have compatibility with FE?

**Comment by Videonauth** [comment]
Well I just did some testing because I face the same problem, and the two mods I'm using for charging other stuff is Induction Charger (which sadly runs on RF) and I tested the Charge-Bench from TechReborn mod (which runs on FE)  on 1.11.2  the Induction Charger Accepts the Item but does not load it, and the Charge Bench which probably could charge the Hammer does not accept it in its UI.

**Comment by thebrightspark** [comment]
I've had a look at the source code for the Charge Bench from Tech Reborn, and I think I see my issue. I may have misunderstood how I'm meant to be using the Forge Energy capability XD So fixing that would allow it to be put in the GUI, however I don't see anything for charging an item with the capability. So I'll try fix it to use the proper capability and see where we get with that.

**Comment by thebrightspark** [comment]
Right, I think I've correctly implemented the Forge Energy capability into the Powered Hammer now, and I can put it into the Tech Reborn Charging Bench, however it does not charge in my testing. Perhaps you have more things you could test it with? It's in the latest release, v1.6.4 for both 1.10.2 and 1.11.2.
I also know there's an issue where the fully powered hammer in the creative tab isn't powered when you take one... I don't know why that's happening unfortunately.

If all else fails, I'll add the RF API for wider support, but I was hoping to not need to do that.

**Comment by Videonauth** [comment]
Being kinda busy in real life right now but will test it as soon I got a moment to spare.

**Comment by jubalearly** [comment]
Just tested 1.6.4.  Cannot get it to charge in either Actually Additions Energizer, TE Infuser, RFTools powercell or Enderio capacitor bank.

**Comment by thebrightspark** [comment]
Okay, so I guess most mods are not fully implementing the Forge Energy capability yet :(
I'll get the RF API implemented and out in a hotfix within a few hours.

**Comment by thebrightspark** [comment]
Okay, I've just released the latest version (v1.6.5) for 1.10.2 and 1.11.2 which adds RF compatibility.
I have tested using the Immersive Engineering Charger, and it looks like it works fine :).

FYI I did actually find a issue in the process with the energy capability which meant the energy wasn't actually being saved... so now that should work.
