### ISSUE TITLE
Had too much fun with the nether star hammer

### ISSUE THREAD

**Issue by TheGuyFromTheInternet** [thebrightspark/SparksHammers#22]
I eventually crashed my game after a back to back use of the nether star hammer. It was the best thing but this happened. Rip.

---- Minecraft Crash Report ----

WARNING: coremods are present:
  llibrary (llibrary-1.7.4-1.11.2.jar)
  CCLCorePlugin (CodeChickenLib-1.11.2-2.6.0.254-universal.jar)
  literalascension (literalascension-1.11.2-1.0.1.1.jar)
  offlineskins (OfflineSkins-1.11.2-v1.jar)
  RBLoadingPlugin (RealBench-1.11.2-1.3.2.jar)
  ForgelinPlugin (Forgelin-1.4.1.jar)
Contact their authors BEFORE contacting forge

// Ooh. Shiny.

Time: 4/20/17 12:41 PM
Description: Ticking player

java.lang.NullPointerException: Ticking player
	at com.brightspark.sparkshammers.handlers.BlockEventHandler.onBlockBreak(BlockEventHandler.java:86)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_115_BlockEventHandler_onBlockBreak_BreakEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185)
	at net.minecraftforge.common.ForgeHooks.onBlockBreakEvent(ForgeHooks.java:785)
	at net.minecraft.server.management.PlayerInteractionManager.func_180237_b(PlayerInteractionManager.java:286)
	at net.minecraft.server.management.PlayerInteractionManager.func_73075_a(PlayerInteractionManager.java:112)
	at net.minecraft.entity.player.EntityPlayerMP.func_70071_h_(EntityPlayerMP.java:272)
	at net.minecraft.world.World.func_72866_a(World.java:1963)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:840)
	at net.minecraft.world.World.func_72870_g(World.java:1932)
	at net.minecraft.world.WorldServer.func_184147_l(WorldServer.java:650)
	at net.minecraft.world.World.func_72939_s(World.java:1724)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:621)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:720)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:624)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:149)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:482)
	at java.lang.Thread.run(Thread.java:745)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at com.brightspark.sparkshammers.handlers.BlockEventHandler.onBlockBreak(BlockEventHandler.java:86)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_115_BlockEventHandler_onBlockBreak_BreakEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185)
	at net.minecraftforge.common.ForgeHooks.onBlockBreakEvent(ForgeHooks.java:785)
	at net.minecraft.server.management.PlayerInteractionManager.func_180237_b(PlayerInteractionManager.java:286)
	at net.minecraft.server.management.PlayerInteractionManager.func_73075_a(PlayerInteractionManager.java:112)
	at net.minecraft.entity.player.EntityPlayerMP.func_70071_h_(EntityPlayerMP.java:272)
	at net.minecraft.world.World.func_72866_a(World.java:1963)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:840)
	at net.minecraft.world.World.func_72870_g(World.java:1932)

-- Player being ticked --
Details:
	Entity Type: null (net.minecraft.entity.player.EntityPlayerMP)
	Entity ID: 1849
	Entity Name: TheInternetGuy
	Entity's Exact location: -109963.13, 14.00, -99328.62
	Entity's Block location: World: (-109964,14,-99329), Chunk: (at 4,0,15 in -6873,-6209; contains blocks -109968,0,-99344 to -109953,255,-99329), Region: (-215,-195; contains chunks -6880,-6240 to -6849,-6209, blocks -110080,0,-99840 to -109569,255,-99329)
	Entity's Momentum: 0.00, -0.08, 0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.world.WorldServer.func_184147_l(WorldServer.java:650)
	at net.minecraft.world.World.func_72939_s(World.java:1724)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:621)

-- Affected level --
Details:
	Level name: Testing
	All players: 1 total; [EntityPlayerMP['TheInternetGuy'/1849, l='Testing', x=-109963.13, y=14.00, z=-99328.62]]
	Chunk stats: ServerChunkCache: 899 Drop: 0
	Level seed: 3644115127423931817
	Level generator: ID 00 - default, ver 1. Features enabled: true
	Level generator options: 
	Level spawn location: World: (128,64,256), Chunk: (at 0,4,0 in 8,16; contains blocks 128,0,256 to 143,255,271), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 28131 game time, 28131 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 10886 (now: false), thunder time: 83618 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:720)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:624)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:149)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:482)
	at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
	Minecraft Version: 1.11.2
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 250149040 bytes (238 MB) / 1060372480 bytes (1011 MB) up to 1060372480 bytes (1011 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	IntCache: cache: 1, tcache: 1, allocated: 12, tallocated: 94
	FML: MCP 9.38 Powered by Forge 13.20.0.2282 54 mods loaded, 54 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	minecraft{1.11.2} [Minecraft] (minecraft.jar) 
	UCHIJAAAA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.11.2-13.20.0.2282.jar) 
	UCHIJAAAA	forge{13.20.0.2282} [Minecraft Forge] (forge-1.11.2-13.20.0.2282.jar) 
	UCHIJAAAA	ccl-entityhook{1.0} [ccl-entityhook] (CodeChickenLib-1.11.2-2.6.0.254-universal.jar) 
	UCHIJAAAA	barkifier{1.3.2} [Barkifier] (Barkifier MC1.11.2 v1.3.2.jar) 
	UCHIJAAAA	betterthanmending{@VERSION@} [Better Than Mending] (BetterThanMending-1.0.0.jar) 
	UCHIJAAAA	ceramics{1.11.2-1.2.0} [Ceramics] (Ceramics-1.11.2-1.2.0.jar) 
	UCHIJAAAA	codechickenlib{2.6.0.254} [CodeChicken Lib] (CodeChickenLib-1.11.2-2.6.0.254-universal.jar) 
	UCHIJAAAA	chickenchunks{2.3.0.63} [ChickenChunks] (ChickenChunks-1.11.2-2.3.0.63-universal.jar) 
	UCHIJAAAA	shadowmc{3.7.1} [ShadowMC] (ShadowMC-1.11.2-3.7.5.jar) 
	UCHIJAAAA	clipboard{@VERSION@} [Clipboard] (Clipboard-1.11-1.2.1.jar) 
	UCHIJAAAA	coralreef{1.0} [Coral Reef] (CoralReef-1.4.jar) 
	UCHIJAAAA	craftablehorsearmour{1.3} [Craftable Horse Armour [CHA&S]] (CraftableHorseArmor-1.3.0-1.11.jar) 
	UCHIJAAAA	crystalcaves{1.0} [Crystal Caves] (CrystalCaves-1.0.jar) 
	UCHIJAAAA	cyclopscore{0.10.0} [Cyclops Core] (CyclopsCore-1.11.2-0.10.0.jar) 
	UCHIJAAAA	dirt2path{1.5.0} [Dirt2Path] (dirt2path-1.5.0.jar) 
	UCHIJAAAA	easybreeding{4.1.0} [EasyBreeding] (easybreading-1.11.2-4.1.0.jar) 
	UCHIJAAAA	elevatorid{1.3.0} [Elevator Mod] (ElevatorMod-1.11.2-1.3.0.jar) 
	UCHIJAAAA	fecm{1.0.0} [Elytra Crafting Recipe Mod] (Elytra Crafting Mod-1.0.0.jar) 
	UCHIJAAAA	csb_ench_table{1.0} [Lapis Stays in the Enchanting Table] (EnchantingTable-1.11-1.0.jar) 
	UCHIJAAAA	extrarails{1.2.1} [Extra Rails] (ExtraRails-1.11-1.2.1.jar) 
	UCHIJAAAA	fastleafdecay{v12} [Fast Leaf Decay] (FastLeafDecay-v12.jar) 
	UCHIJAAAA	felling{1.0} [Felling] (felling-1.0.jar) 
	UCHIJAAAA	forgelin{1.4.1} [Forgelin] (Forgelin-1.4.1.jar) 
	UCHIJAAAA	fishing{1.5.1} [Fishing Net Mod] (GiacomosFishingNet-1.11.2-1.5.1.jar) 
	UCHIJAAAA	gravestone{1.7.2} [Gravestone] (GraveStone Mod 1.7.2.jar) 
	UCHIJAAAA	gud_clear_jukebox{1.0.0.1} [Clear Jukebox] (gud_clear_jukebox-1.0.0.1.jar) 
	UCHIJAAAA	hopperducts{1.4.9} [Hopper Ducts] (hopperducts-mc1.11.2-1.4.9.jar) 
	UCHIJAAAA	waila{1.8.13} [Waila] (Hwyla-1.8.13-B26_1.11.jar) 
	UCHIJAAAA	ironchest{1.11.2-7.0.18.800} [Iron Chest] (ironchest-1.11.2-7.0.18.800.jar) 
	UCHIJAAAA	jei{4.3.2.263} [Just Enough Items] (jei_1.11.2-4.3.2.263.jar) 
	UCHIJAAAA	jeresources{0.6.2.104} [Just Enough Resources] (JustEnoughResources-1.11.2-0.6.2.104.jar) 
	UCHIJAAAA	llibrary{1.7.4} [LLibrary] (llibrary-1.7.4-1.11.2.jar) 
	UCHIJAAAA	literalascension{1.11.2-1.0.1.1} [Literal Ascension] (literalascension-1.11.2-1.0.1.1.jar) 
	UCHIJAAAA	llor{1.1.3-mc1.11.2} [Light Level Overlay Reloaded] (LLOverlayReloaded-1.1.3-mc1.11.2.jar) 
	UCHIJAAAA	mineturtle{1.11-1.0.2} [Mine Turtle] (mineturtle-1.11-1.0.2.jar) 
	UCHIJAAAA	minicoal{1.0} [MiniCoal] (minicoal-1.11.2-1.0.jar) 
	UCHIJAAAA	nmsot{1.2.0-mc1.11.2} [No Mob Spawning on Trees] (NoMobSpawningOnTrees-1.2.0-mc1.11.2.jar) 
	UCHIJAAAA	samsocean{1.0.1} [Ocean Floor Classic] (OceanFloor-1.11-1.0.1.jar) 
	UCHIJAAAA	offlineskins{1.11.2-v1} [OfflineSkins] (OfflineSkins-1.11.2-v1.jar) 
	UCHIJAAAA	railsplus{1.0.0} [Rails Plus] (railsplus-1.0.1.jar) 
	UCHIJAAAA	simplecobblegen{1.11.2-2.0.0} [Simple Cobblestone Generator] (SimpleCobbleGen-1.11.2-2.0.0.jar) 
	UCHIJAAAA	snad{1.11.2-1.7.03.26a} [Snad] (Snad-1.11.2-1.7.03.26a.jar) 
	UCHIJAAAA	sparkshammers{1.11.2-1.6.3.1} [Spark's Hammers] (sparkshammers-1.11.2-1.6.3.1.jar) 
	UCHIJAAAA	spartanshields{1.3} [Spartan Shields] (SpartanShields-1.11.2-1.3a.jar) 
	UCHIJAAAA	stg{1.11.2-1.1.1} [SwingThroughGrass] (stg-1.11.2-1.1.1.jar) 
	UCHIJAAAA	structuredcrafting{0.1.7} [Structured Crafting] (StructuredCrafting-1.11.2-0.1.7.jar) 
	UCHIJAAAA	teletoro{1.11.2-22} [TeleToro] (teletoro-1.11.2-22.jar) 
	UCHIJAAAA	torcharrowsmod{1.9.4-2} [TorchArrowsMod] (torcharrows-1.11.2-2.jar) 
	UCHIJAAAA	torchmaster{1.0} [TorchMaster] (torchmaster_1.11.2-1.2.1.24.jar) 
	UCHIJAAAA	villagerinventory{1.0.3} [Villager Inventory Viewer] (VillagerInventory-1.11-1.0.3.jar) 
	UCHIJAAAA	witherskelefix{1.6.2} [Wither Skeleton Tweaks] (Wither Skeleton Tweaks-1.11.2-1.6.2.jar) 
	UCHIJAAAA	xpbook{0.0.2-beta} [XPBook] (xpbook-1.11.2-0.0.2-beta.jar) 
	Loaded coremods (and transformers): 
llibrary (llibrary-1.7.4-1.11.2.jar)
  net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
  net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
CCLCorePlugin (CodeChickenLib-1.11.2-2.6.0.254-universal.jar)
  codechicken.lib.asm.ClassHierarchyManager
  codechicken.lib.asm.CCL_ASMTransformer
literalascension (literalascension-1.11.2-1.0.1.1.jar)
  com.jamieswhiteshirt.literalascension.core.patcher.LiteralAscensionRuntimePatcher
offlineskins (OfflineSkins-1.11.2-v1.jar)
  lain.mods.skins.asm.ASMTransformer
RBLoadingPlugin (RealBench-1.11.2-1.3.2.jar)
  pw.prok.realbench.asm.RBTransformer
ForgelinPlugin (Forgelin-1.4.1.jar)
  
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	chickenchunks Invalid Fingerprint Reports: - No invalid fingerprints.: 
	Profiler Position: N/A (disabled)
	Player Count: 1 / 8; [EntityPlayerMP['TheInternetGuy'/1849, l='Testing', x=-109963.13, y=14.00, z=-99328.62]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'

**Comment by thebrightspark** [comment]
I can't reproduce this, can you tell me exactly what you were doing to make this happen please?

**Comment by TheGuyFromTheInternet** [comment]
Sorry. I was drilling under the map nonstop since it was so satisfying to see that hammer drill through so much stuff. In the near end of it though, the breaking effect of the hammer started stuttering. Maybe it's because of a ram issue since the computer I used wasn't the best for modded minecraft.

Is there no issue when the nether star hammer is used in different directions as quickly as possible. The enchantments I had on the hammer were mending and unbreaking 3. I also had a mod n called Better Mending which lets me heal the hammer by shift clicking to drain my xp.

**Comment by thebrightspark** [comment]
I still don't understand how you've caused this issue, however I've rewritten some parts for the Nether Star Hammer so it should work better now. These changes are in the latest version, v1.6.4 for both MC 1.10.2 and 1.11.2. Please let me know if it works or not. If not, please describe exactly what you do. Perhaps even a video or GIF showing what happens would be ideal?

**Comment by thebrightspark** [comment]
Closing this due to no response in a very long time.
