### ISSUE TITLE
how to get the mjolnir?

### ISSUE THREAD

**Issue by ghost** [thebrightspark/SparksHammers#24]
u wrote nothing in wiki about how to get it. please help, thanks...

**Comment by thebrightspark** [comment]
I did, and even added a picture. I kept it a little vague though for those who may prefer the challenge of finding it themselves. So I can understand if this isn't enough for you.
Mjolnir can only be found in the shrines (like in the picture) in the overworld at Y levels higher than 125, and have a 1 in 50 chance of spawning by default.
You cannot pickup Mjolnir until you've defeated the Ender Dragon (to be "worthy"). Also you can't pickup a Mjolnir already owned by another player.

**Comment by ghost** [comment]
thanks a lot, i just checked the Mjolnir section in wiki..
