### ISSUE TITLE
No hammers to craft.

### ISSUE THREAD

**Issue by TheGooblyGoob** [thebrightspark/SparksHammers#25]
I downloaded it, and the mod is in there and it is fully functional; However, the only things that come with the mod is Mjolnir in it's block/placeable form, the crafting table for the hammers (when the recipe is pulled up there is no wooden hammer in the middle) and the magical wand to summon mjolnir.

**Comment by thebrightspark** [comment]
What version of the mod are you using? And what Forge version?

EDIT:
Infact, before you tell me that, can you try and delete the my mod's config folder and then load up and try again?

**Comment by TheGooblyGoob** [comment]
Okay, I'll try that. hold on one minute

**Comment by TheGooblyGoob** [comment]
There is no way for me to get into the config through the mods menu. I'm using the newest forge version and I'm using the latest sparks hammers release.

**Comment by TheGooblyGoob** [comment]
Forge 1.11.2-13.20.0.2298 and Sparks-Hammers-Mod-1.11.2

**Comment by TheGooblyGoob** [comment]
It won't let me upload the files so I figured i'd just say what they were

**Comment by thebrightspark** [comment]
When I said about deleting the configs, I meant for you to actually go to your pack's directory and find the config files yourself - it's the only way. You'll find my config folder at:
_(packDirectory)_/config/sparkshammers

Oh I wouldn't have wanted the files. Just wanted to know the versions, so thank you for telling me those.
Before I do any testing, I would still like you please to delete the configs as I said above and see if that fixes your issue.

**Comment by TheGooblyGoob** [comment]
I went into the config folder, tried deleting each individual cfg inside the file, and I tried deleting the whole file, and it did not fix the issue.

**Comment by thebrightspark** [comment]
Oh btw you only said the MC version that my mod is for. What's the actual mod version?

**Comment by thebrightspark** [comment]
I just created a custom pack using the same Forge version and my latest mod version (1.6.5) and everything's fine. Are you using any other mods too?

**Comment by TheGooblyGoob** [comment]
I'm using a lot of other mods. Like 20 mods.

**Comment by thebrightspark** [comment]
20 isn't a lot ;D
Can you try my mod on it's own (or at with JEI if you want) and see if that works? If that works, then some other mod you have is doing something funny which isn't playing nice with mine. If you can find out which mod is causing the issue, please let me know :)

**Comment by TheGooblyGoob** [comment]
Okie dokes. Only mod I could think of that could do anything with yours would be funores just because of the different kind of hammers that allows me to make.

**Comment by TheGooblyGoob** [comment]
It didn't work :(

**Comment by thebrightspark** [comment]
As in, you made a pack with just my mod (and maybe JEI) and the mod still doesn't show everything in game?

**Comment by TheGooblyGoob** [comment]
The only 2 mods that were loaded were your mod and jei. I opened jei and there was only the wand, the block mjolnir, and the crafting table. Theres not a single hammer in there. When i open the recipe for the hammer crafting table there isnt even a wooden hammer in the middle. Can you send a link for another download and let me see if that one works

**Comment by thebrightspark** [comment]
Well I used the download from Curse. Anything else I send you will be the exact same.

Can you post your latest FML log? Pretty sure that's the one which shows the games console output.
Please post it using pastebin.com and link it back here.

**Comment by TheGooblyGoob** [comment]
I downloaded and used the one from curse and the same issue is occuring. How do I get you the FML log. (I'm a total computer noob, just remember this)

**Comment by thebrightspark** [comment]
If you go to the mod pack folder, there should be a folder called "logs", and in there you'll want to get the latest log which should be in a .txt file.
(FYI I'm not at my computer atm so I can't check this myself)

**Comment by TheGooblyGoob** [comment]
Okay, just a moment.

**Comment by TheGooblyGoob** [comment]
[2017-05-17-7.log.gz](https://github.com/thebrightspark/SparksHammers/files/1009449/2017-05-17-7.log.gz)

**Comment by thebrightspark** [comment]
No not one ending in .gz - I can't open those.
There should be one just called "latest" which is a text file.

**Comment by TheGooblyGoob** [comment]
Well jeez now it's working. I downloaded the 1.6 one yesterday to see if that would work and it did so I played with that and then reinstalled the latest one so I could open and show you that text file. it's working now. Thank you so much for your time! I really do appreciate it.

**Comment by thebrightspark** [comment]
Ah good, glad it's all working fine now :)
