### ISSUE TITLE
Recipes not showing up in JEI 1.12

### ISSUE THREAD

**Issue by seamuskomeara** [thebrightspark/SparksHammers#27]
Hammers and hammer crafting station recipes do not show up in JEI in Minecraft v1.12 with the latest version of both JEI and Hammers installed as of 14/5/17

**Comment by thebrightspark** [comment]
Read the changelog. I have removed them for this version until I get them working.

**Comment by seamuskomeara** [comment]
Fair. Sorry about that all my fault

**Comment by ircmaan** [comment]
Excuse mua - I can not find this issue because it is _closed_.  Do not close one issue named like "Can not craft some hammers in 1.12" and we do not write issue like it. :)  
Thanx for your work!

**Comment by thebrightspark** [comment]
@ircmaan You can look at the closed issues...

**Comment by ircmaan** [comment]
All my life I think "closed issue" = "fixed issue"

**Comment by thebrightspark** [comment]
No, "closed issue" = "resolved issue" (At least to me)
Not necessarily fixed.
