### ISSUE TITLE
Recipes

### ISSUE THREAD

**Issue by TookUrSweetRoll** [thebrightspark/SparksHammers#28]
No recipes in JEI. Cannot craft hammers or table. Tried using recipe pics from google to craft with no luck. 
Minecraft 1.12, Sparks 1.65, Forge 2327 (latest)

**Comment by thebrightspark** [comment]
Please...
1) Look at the changelog
2) Look at previous issues
#27

**Comment by TookUrSweetRoll** [comment]
Apologies. Joined GitHub today to ask this question. Didn't even see the closed issues section. Facepalm. Love the mod. Keep up the good work.
