### ISSUE TITLE
In 1.12 I can not craft any hammer in the Hammer Crafting Table.

### ISSUE THREAD

**Issue by ircmaan** [thebrightspark/SparksHammers#29]
Subj.
Is this recipes still good?
https://camo.githubusercontent.com/8498a1442a38b90b7cfe780aa8605e54a49e7f74/687474703a2f2f692e696d6775722e636f6d2f764370493854742e706e67
https://camo.githubusercontent.com/9a0dd83efc5c1b9355537f045604e33899b47115/687474703a2f2f692e696d6775722e636f6d2f515066303558472e706e67
etc.

**Comment by thebrightspark** [comment]
Please make sure you read old issues and check changelog before posting here...
#27

**Comment by ircmaan** [comment]
It is a good mod. We like it but...
1. I have read all the issue before and I can not find issue like my.
2. "check changelog" But where?
Thanx anyway.

**Comment by thebrightspark** [comment]
I linked the related issue in my previous message.
You can find the changelogs when you click on a file in the file list on the mod's CurseForge page, [like here for 1.12](https://minecraft.curseforge.com/projects/sparks-hammers/files/2432705).

Or if you're using the Twitch client, you can see the changelog for the most recent version on the "Changelogs" tab on the mod.

**Comment by ircmaan** [comment]
In 1.12 Twich
"- Added RF compatibility to the Powered Hammer
- Powered Hammer now actually keeps it's energy"
I see only this changelog - thats why I opened that issue. I didn't want to disturb you.
Can you write "In 1.12 Temporarily removed achievements, recipes and JEI integration." on the main page? Thanx.

**Comment by thebrightspark** [comment]
That's probably because alpha builds don't get synced to the Twitch clients. And this certain version is alpha for a reason... plus Forge isn't even in a stable state to be played on yet. These current Forge versions are meant only for modders.

So thinking on that, I don't see the need to, because Forge for 1.12 is too unstable anyway and due to that I can't guarantee anything will work yet.
