### ISSUE TITLE
Recipes on Forge 2443

### ISSUE THREAD

**Issue by ghost** [thebrightspark/SparksHammers#32]
no recipes on jei for sparks hammers except hammer crafting table and wood things.
MC 1.12.
sh 1.6.5.1

**Comment by thebrightspark** [comment]
Yes that's because I haven't re-implemented the JEI integration. Not a bug, just haven't gotten to it yet.

**Comment by ghost** [comment]
oh ok sorry, i saw the changelog that tells "fixed recipes" then tought this.
