### ISSUE TITLE
Still crashes on 1.12 with forge 2405

### ISSUE THREAD

**Issue by MoonCutter2B** [thebrightspark/SparksHammers#34]
Got this error:
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Redstone Flux (redstoneflux)
Caused by: java.lang.RuntimeException: 
RedstoneFlux has detected that the following OLD API classes from CoFHLib are being repacked!
    cofh.api.energy.ItemEnergyContainer, loaded from: sparkshammers-1.12-1.6.6.jar
    cofh.api.energy.EnergyStorage, loaded from: sparkshammers-1.12-1.6.6.jar
    cofh.api.energy.TileEnergyHandler, loaded from: sparkshammers-1.12-1.6.6.jar
    cofh.api.energy.IEnergyConnection, loaded from: sparkshammers-1.12-1.6.6.jar
    cofh.api.energy.IEnergyProvider, loaded from: sparkshammers-1.12-1.6.6.jar
    cofh.api.energy.IEnergyHandler, loaded from: sparkshammers-1.12-1.6.6.jar
    cofh.api.energy.IEnergyStorage, loaded from: sparkshammers-1.12-1.6.6.jar
    cofh.api.energy.IEnergyContainerItem, loaded from: sparkshammers-1.12-1.6.6.jar
    cofh.api.energy.IEnergyReceiver, loaded from: sparkshammers-1.12-1.6.6.jar

To prevent this crash, add "-Dcofh.rf.crashOnOldAPI=false" to your command line arguments.

	at cofh.redstoneflux.internal.OldAPIChecker.check(OldAPIChecker.java:64)
	at cofh.redstoneflux.RedstoneFlux.preInit(RedstoneFlux.java:25)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
...

**Comment by Morpheus1101** [comment]
Its because the mod is using an old API from cofh, which they need to remove OR do as the instructions say an add the `-Dcofh.rf.crashOnOldAPI=false` into your jvm arguments an you'll be fine

**Comment by covers1624** [comment]
Representing CoFH here, You need to update and depend on the new API not repack it, https://minecraft.curseforge.com/projects/redstone-flux For more info. 

The `-Dcofh.rf.crashOnOldAPI=false` is to provide users with a way to still play the game with the old api present but it will be functionally incompatible with the actual released RF.

**Comment by thebrightspark** [comment]
Thanks for all the help guys, I've fixed this in the commit https://github.com/thebrightspark/SparksHammers/commit/28afd424d10403fb47e508debc2644aa84bfcfdd
