### ISSUE TITLE
[1.12] Sparkshammer's items appear in all creative tabs

### ISSUE THREAD

**Issue by Morpheus1101** [thebrightspark/SparksHammers#35]
This is a minor thing and common in 1.12, but all items from this mod appear in all mods creative tabs

**Comment by thebrightspark** [comment]
All items? I can only replicate this for the Powered Hammer at full charge. It appears in most creative tabs, however I have no idea why.

**Comment by thebrightspark** [comment]
Fixed for version 1.6.6.2 thanks to @Zundrel :)
