### ISSUE TITLE
Repairs

### ISSUE THREAD

**Issue by Truzedo** [thebrightspark/SparksHammers#37]
Can spark hammers be repaired?  Or do you just have to replace when durability is gone?

**Comment by thebrightspark** [comment]
I believe the tools can be repaired. I see it in my code, but I haven't tested it for a while. Every tool, if possible (and excluding Mjolnir) should be repairable. The special hammers should have the following repair materials:
- Mini Hammer -> Iron Ingot
- Giant Hammer -> Iron Block
- Powered Hammer -> Iron Block
- Nether Star Hammer -> Nether Star

All other hammers which are repairable should be able to be repaired using the material that's used to make them.

If this is broken please let me know!
