### ISSUE TITLE
Not working on forge server?

### ISSUE THREAD

**Issue by sillymonkeydesigns** [thebrightspark/SparksHammers#38]
I have version 1.12-1.6.6.2 and it works just fine on minecraft v 1.12.2 single player, however on the forge server it does not work at all?

**Comment by thebrightspark** [comment]
Probably because SparksHammers is only built for MC 1.12 and not 1.12.2 yet, so no surprise.
I've been neglecting this mod for a while, but I'll see about updating it for 1.12.2 soon to sort this.

**Comment by thebrightspark** [comment]
Not sure if this is an issue... I'm using the latest version of SparksHammers fine on a 1.12.2 server with around 100 mods.
Will close this, but post if you can provide proof that my mod is causing the issue and I'll reopen.
