### ISSUE TITLE
a feature request

### ISSUE THREAD

**Issue by comical-uk** [thebrightspark/SparksHammers#39]
Hi

this isn't a bug but I wasn't sure where to suggest it

would it be possible to, when you have a hammer equipped, to be able to right click and it will place a vanilla torch if there are any in your inventory

Love the mod, cheers!

**Comment by thebrightspark** [comment]
Sure, I'd probably make it configurable for the option to keep it closer to vanilla style tools though.

**Comment by comical-uk** [comment]
brilliant, thanks

**Comment by thebrightspark** [comment]
This will be in the next released version.
Added the feature in commit https://github.com/thebrightspark/SparksHammers/commit/f6bca2711f4a085d39fbb958ca9ef87ebb9a8111.

Just bear in mind that the feature is disabled by default.
