### ISSUE TITLE
Mjolnir Doesn't Require Anything?

### ISSUE THREAD

**Issue by ghost** [thebrightspark/SparksHammers#40]
i created a new world then found the mjolnir and right clicked, then its mine. don't i have to kill end dragon to have this? using forge 2604, maybe you should update forge...dunno...

**Comment by thebrightspark** [comment]
Nothing is wrong, I just haven't implemented advancements for the mod yet after updating to 1.12.
I had everything involving the old achievements disabled until I replaced it with advancement support.
You can expect it in the next update once I finish it :)
