### ISSUE TITLE
Ghost Tool Issues

### ISSUE THREAD

**Issue by Gelles** [thebrightspark/SparksHammers#43]
Using the 1.7 version of Sparks Hammers and the recommended (14.23.2.2611) version of Forge, no other mods installed.

The first time you make a tool upon world load, it crafts as expected, but when you try to use the tool (hammer or excavator), the blocks will flash but only the central block will break, and the tool will not take any durability damage. Attempting to click on the tool in your inventory causes it to vanish.

Also, once you craft a tool, you can't make another tool of that same material unless you relog (ie, you can craft one diamond hammer but then the recipe stops working if you try to craft a second one; the output slot on the hammer crafting table remains empty, like the recipe is invalid).

Another weird thing I've noticed is that if you have multiple crafting items in the slots (like more than four sticks) once you craft the tool, you get back more than used (see screenshots).

![2018-02-22_16 37 33](https://user-images.githubusercontent.com/7891001/36568224-ca4ba18a-17ee-11e8-85ff-6279e4eb2f7f.png)
![2018-02-22_16 37 36](https://user-images.githubusercontent.com/7891001/36568227-cd9941e4-17ee-11e8-8dcf-bd7b70c9e8a8.png)

**Comment by thebrightspark** [comment]
This has been fixed in commit https://github.com/thebrightspark/SparksHammers/commit/4b2a9ea4b4f5631cd48552d45e00de7e19b56830
