### ISSUE TITLE
Odd Glitch

### ISSUE THREAD

**Issue by TheGooblyGoob** [thebrightspark/SparksHammers#44]
I've crafted a couple hammers and it happens with each one. I'll craft it in the hammer workbench, and then after I shift click it into my inventory I'll go to move things around so it's in the correct inventory slot. After I click the hammer it'll uncraft and put all the parts back into the workbench, sometimes gets rid of the parts completely and I'm down 10 of that metal, and it won't let me make that hammer with that specific kind of metal.

**Comment by thebrightspark** [comment]
Can't reproduce this... if this is still happening, please provide a list of all the mods you have installed and their versions and I'll try it again with the mods.
