### ISSUE TITLE
Disabling mod hammers, disabled more than it should.

### ISSUE THREAD

**Issue by 8BrickDMG** [thebrightspark/SparksHammers#45]
I noticed when I disabled the mod item hammers in the config, this caused all vanilla style hammers to be disabled also.

![2018-04-03_14 32 29](https://user-images.githubusercontent.com/7628776/38252528-4c234218-374c-11e8-9b16-da06fd915b6b.png)

**Comment by thebrightspark** [comment]
I've removed this config option now. You can just control this by removing the tools from the customTools.json.
