### ISSUE TITLE
Lumber axe?

### ISSUE THREAD

**Issue by Bullorg74** [thebrightspark/SparksHammers#46]
Hi dont know how much you are working on this mod but I lumber axe (axe that cut down the entire tree) addition would be great.
Then this mod have all you need really (in tools) to totally replace Tinkers.

I'm using the mod in a pack at the moment and a lumberaxe would be amazing.

Still mostly a idea. 
Great mod TY

**Comment by thebrightspark** [comment]
I won't ever add a Lumber Axe or any other type of tool to SparksHammers.

However, I may at some point discontinue the mod in favour of a more general mod that has hammers, excavators, and other tools like lumber axes. However that's when I have the time to want to re-write the mod.

**Comment by Bullorg74** [comment]
Thank you for answering.
As I said. just a idea.

And I really like the mod as it is.

**Comment by ghost** [comment]
@Bullorg74 Not to necro, but there are a few mods that add lumberaxes.

Personally, I'm enjoying being away from TiCon, it makes things like enchantability a thing again. And with Spark's "Deault Enchantments" mod you can add redstone hammers with builtin haste and lapis hammers with luck if you want.

I just wanted to plug Chop Down Updated. When you cut down a tree, or just a log pole, it falls away from you bringing the leaves and everything with it. It's pretty cool and even works on large trees. You still have to chop them, but no more climbing for floating logs hidden in leaves.
