### ISSUE TITLE
Stone Hammer can mine Obsidian Mining Level Blocks

### ISSUE THREAD

**Issue by davqvist** [thebrightspark/SparksHammers#47]
MC 1.12.2
Forge 2654
SH 1.7.1

A Stone Hammer can't mine Obsidian, but can mine Obsidian Mining Level (or higher) Blocks from other mods like Cobalt from Tinkers Construct or Hornblende Idolum from Primal Core.

**Comment by thebrightspark** [comment]
I've actually already been updating the core tool logic around this, so chances are that this already fixed in the next release.

Let me know then if you still encounter the same issue.

**Comment by thebrightspark** [comment]
This should hopefully be fixed in the most recent version (1.8.0).
Re-open and let me know if not.
