### ISSUE TITLE
2 Mjolnir glitches

### ISSUE THREAD

**Issue by BrailleCortex** [thebrightspark/SparksHammers#48]
Minecraft version 1.12.2, mod version 1.7.1
1. When placing an enchanted Mjolnir on the ground, the enchantments are lost upon picking it up again.
2. When dropping Mjolnir through an End portal from the overworld, entering the End causes unrecoverable world files in singleplayer and corrupted region files in multiplayer.

**Comment by thebrightspark** [comment]
Fixed both with the respective commits:
d2d314207544bde554a39598b294bd5008e89b82
f4be60c441f9ea65bcd32e0680646eeaf57d9025

Just an FYI I completely disabled enchanting Mjolnir, as originally intended.
