### ISSUE TITLE
Update of Mantle has broken Sparks Hammers

### ISSUE THREAD

**Issue by grydian** [thebrightspark/SparksHammers#5]
I updated to version Mantle-1.10.2-1.1.0 of Mantle inline with their new harvestweaks mod release.  I actually had this error just updating Mantle.  I saw this mod was released and I had hopes it would fix the problem.  So I went in and updated the config adding all the tools from this mod.  Should have tested...  lol  Oh well none of it worked and I cannot mine stone with any of the hammers.  I am using SparksHammers-1.10.2-1.3.1 and the latest version of forge 2107.

**Comment by thebrightspark** [comment]
I have just tested in my current dev environment (MC v1.10.2) with the same version of Mantle and I do not have this issue. Is it still an issue you have?

**Comment by grydian** [comment]
Just tested with latest forge (2171) latest tinkers (2.5.6b) and mantle (1.1.2) and the stone and wooden hammer have a red "pickaxe" in walia instead of a green one.  Its like the tool is not considered a "pickaxe" type tool.  So I can't mine and progress through the game with early hammers.

**Comment by grydian** [comment]
Fyi Still have this problem with my current pack.  Using latest forge/sparks and mantle.  Any chance you can fix this?

**Comment by thebrightspark** [comment]
I'm a little confused. I'm using Sparks Hammers with Harvest Tweaker (same versions as you were using) and I'm able to mine dirt and stone fine with wooden and stone tools. Is there something I'm missing? I know Waila shows it's the wrong tool type (I don't know why atm and it's not a big enough issue for me to worry about atm) but it'll work anyway.

**Comment by thebrightspark** [comment]
Closing this due to no response in a very long time.
