### ISSUE TITLE
"DependantStackId" from custom tools.json doesn't generate Hammers/Excavators for the used material item id.

### ISSUE THREAD

**Issue by TripleTomTv** [thebrightspark/SparksHammers#50]
Whenever i try to add Hammers/Excavators via the "DependantStackId" option instead of the "DependantOreDic" option in the custom tools.json file, the hammers don't get generated.
If i use "DependantOreDic" i always get hammers generated, but if the mod has a material that isn't registered in the ore dictionary, it's impossible to craft the tools.
Using the proper item id from the material doesn't yield hammers and excavators, so currently it's required for the material to be registered in the Ore Dictionary and using the "DependantOreDic" option in the custom tools.json file.

Tried mods so far are:

- **ExtraGems** (Adds Gems which are properly registered as gemNAME in the ore dictionary. Hammers craftable by using their OreDic)
- **Ice and Fire** (Adds Dragons with their respective Armors and Dragonbone Tools using Dragon Bone items which aren't registered in the OreDic, so no ability to craft Dragonbone Hammers, also adds Silver Ore and Tools which are properly registered in the OreDic. Silver Hammers craftable by using its OreDic)
- **Simply Platinum** (Adds Platinum Ore and Tools which are registered in OreDic. Hammers craftable by using its OreDic)
- **Vulcanite** (Adds a Nether Ore which is a gem i think? Nothing in the mod exactly tells what kind of ore it really is. Not even the string item ids. It needs to be smelt though and it isn't registered in the OreDic, so no ability to craft hammers)
- **Galaxite** (Same as Vulcanite but as an End Ore)

It appears to be a bug of some sort, because the "DependantStackId" option was always working just fine in the 1.10.2 and 1.11.2 versions of the mod.

**Comment by thebrightspark** [comment]
Fixed this in commit 761f268d8b9ab1b6065ea2eb40d5adacdbe12320.
Expect it in the next version.
