### ISSUE TITLE
[Suggestion] Option to auto-enchant custom hammers

### ISSUE THREAD

**Issue by ghost** [thebrightspark/SparksHammers#52]
I've been using Sparks as an alternative to TiCon, but I do miss some of the special effects. Would it be possible to get a field in the json to have a custom hammer come with an enchantment already applied? That way we could do things like a lapis hammer with Fortune or a prismarine hammer with aqua affinity.

**Comment by thebrightspark** [comment]
I feel like this is something that'd be better as a separate mod... I'm not sure I really like the idea of that as a feature in Sparks Hammers when I can easily be implemented as its own mod (then you can use it for anything).

It'd actually be very easy to make that as a mod. If you can't find a mod that does it, let me know (PM me on CurseForge or something) and I'll consider making it for you.

**Comment by ghost** [comment]
Thanks for considering and thanks for the offer. I'll see what I can find.
