### ISSUE TITLE
Game crashes when removing Stone Hammer

### ISSUE THREAD

**Issue by Priderino** [thebrightspark/SparksHammers#54]
Removing the Stone Hammer from the config, causes the game to crash:
Crashlog: https://paste.dimdev.org/opunepesul.mccrash
CustomTools: https://paste.dimdev.org/enicuyoles.json

**Comment by thebrightspark** [comment]
Copying my comment from the other issue:

Ah yeah the recipe for the Size Upgrade needs Stone Hammers, so since you removed that hammer, the recipe errors. As a work around for now, you either need to add the Stone Hammer back in or remove the Powered Hammer.

**Comment by thebrightspark** [comment]
Fixed in commit https://github.com/thebrightspark/SparksHammers/commit/5f324b09620c4944eff4806c3bcf02d7dfd5849d
