### ISSUE TITLE
Cobblestone Sparks Hammer

### ISSUE THREAD

**Issue by SwampPanda** [thebrightspark/SparksHammers#55]
The cobble sparks hammer shows a recipe but does not allow a crafting option. When I put all the materials in the hammer crafting station it does not let me get a hammer. Btw I am using 1.12.2 forge.

**Comment by ghost** [comment]
Check the recipe, the current version goes back to using cobblestone instead of compressed cobblestone.

**Comment by thebrightspark** [comment]
Can you use JEI to show the recipe? If nothing is still working as expected, post some screenshots and your customTools.json please
