### ISSUE TITLE
Cobblestone Hammer

### ISSUE THREAD

**Issue by SirArchibald97** [thebrightspark/SparksHammers#57]
When I go to make a cobblestone hammer, it throws all the materials out and takes my hammer. And when I try again, the recipe doesn't work!
Bug?

**Comment by thebrightspark** [comment]
Must be another mod you have that's interfering. What other mods do you have installed?

**Comment by SirArchibald97** [comment]
I have:
 - Tinkers Construct + Mantle
 - JEI
 - Sparks Hammers
 - Optifine
 - Backpacks
 - Ore Core
 - Furniture Mod 

It's probably Tinkers Construct now I come to think of it

**Comment by thebrightspark** [comment]
Just tried with all of the mods mentioned, and works fine
