### ISSUE TITLE
cobblestone hammers only one craft?

### ISSUE THREAD

**Issue by SRASSH** [thebrightspark/SparksHammers#59]
For some reason you can only craft the hammers once with the table.
<img width="719" alt="screen shot 2018-11-18 at 20 17 57" src="https://user-images.githubusercontent.com/45151402/48677601-32bdd900-eb6f-11e8-95ee-d492099f3af9.png">
<img width="559" alt="screen shot 2018-11-18 at 20 18 22" src="https://user-images.githubusercontent.com/45151402/48677602-32bdd900-eb6f-11e8-8aae-2edd3241dd58.png">

**Comment by thebrightspark** [comment]
What versions of Sparks Hammers and Forge are you using? And how exactly did you get to this?
