### ISSUE TITLE
Request for Show Block mining range

### ISSUE THREAD

**Issue by Fireztonez** [thebrightspark/SparksHammers#60]
Hello,
I have your mod in my modpack I currently working on and I really enjoy it!! This is pretty nice to have a mod giving possibility to create like I want and personnalized totally the hammers and Excavator in the pack!!

For now one of the only little thing I saw how can be nice to do, is making a overlay how show what block will be mined. I don't really know how this is called, but when you look a block, ou see the little square showing the block you will mined... With a Tinker or Thermal Fondation hammer's & excavator the square show a 3x3, but with the Spark's hammer, it only show a 1x1, even if it mine 3x3...

You can see here:
With Thermal:
![thermal_3x3](https://user-images.githubusercontent.com/19277301/59981296-30bd6c00-95cf-11e9-8e04-3a6370c18b23.jpg)

With Spark Hammer:
![spark_3x3](https://user-images.githubusercontent.com/19277301/59981310-50ed2b00-95cf-11e9-8287-f58fbe917b79.jpg)

I don't think this is something really hard to do, but this is really usefull to visuially the area you will mined (Even more when you have hammer with bigger area than 3x3)

Thank's

**Comment by thebrightspark** [comment]
Hey, I'd add this but I'm actually working on a re-write of the mod right now under a new name and I actually already have this feature implemented in this! You can check out the repo for it here:
https://github.com/thebrightspark/SparksTools

Here's a screenshot for proof 😉 
![2019-06-23_12 14 11](https://user-images.githubusercontent.com/11932411/59981649-af7dcd80-95fe-11e9-86c2-21e1774308d3.png)
(ignore the almost black looking hammer - it's currently unfinished)
