### ISSUE TITLE
upgrade base

### ISSUE THREAD

**Issue by Juanchoperezlol** [thebrightspark/SparksHammers#62]
Im not able to tell if they have a use at all, crafted a couple of them but I dont know how to apply them. Sorry if this issue its a little silly but I couldnt find info about this anywhere else. Thanks

**Comment by thebrightspark** [comment]
They're just a crafting item to create the actual upgrades. I mention them here:
https://github.com/thebrightspark/SparksHammers/wiki/Powered-Hammer

You should use something like JEI so you can see what they can be crafted into.

**Comment by Juanchoperezlol** [comment]
Thanks!!
