### ISSUE TITLE
Cannot access hammer crafting table, also cannot craft anything other than the two wooden heads.

### ISSUE THREAD

**Issue by AndaleTheGreat** [thebrightspark/SparksHammers#8]
List of installed mods with versions: http://i.imgur.com/kcETHbX.png
Forge 13.19.0.2178 (1.11)

There is a [recipe](http://i.imgur.com/2foQLXR.png) for normal crafting table using the head and two planks which does nothing. Guessing this is the simple version to use without the hammer table.

**Comment by thebrightspark** [comment]
Thanks!

I've fixed this in my latest commit: https://github.com/thebrightspark/SparksHammers/commit/afb68a0aad2f7625e35726ec5b2d1ea5cc148d85

It'll be out in the next version.
